
name: 'demo_dbt'
version: '1.0.0'
config-version: 2

profile: 'ff'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "demo_logs"

models:
  demo_dbt:
      staging:
          +materialized: table
          +schema: staging
          example:
            +tags:
                - p1
                - another_tag
