# profiles.yml
ff:
  outputs:
    dev:
      type: postgres
      account: postgres
      database: postgres
      schema: PUBLIC
      warehouse: compute_wh
      user: postgres
      password: postgres
      threads: 1
      host: localhost
      port: 5432
  target: dev
